branch-defaults:
  default:
    environment: flask-movietweetings13
global:
  application_name: flask-movietweetings
  branch: null
  default_ec2_keyname: MSBA
  default_platform: Python 2.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
